name: CI/CD Pipeline

# Triggers for the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests

      - name: Train Random Forest Model
        run: |
          python scripts/train_rf_model.py

      - name: Train LSTM Model
        run: |
          python scripts/train_lstm_model.py

      - name: Save models
        run: |
          mkdir -p models
          mv rf_model.pkl models/model-2024-06-01-10-36-59.pkl
          mv lstm_model.h5 models/
          mv scaler.pkl models/

      - name: Lint code
        uses: github/super-linter@v3
        env:
          VALIDATE_PYTHON: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/<your-heroku-app>.git
          git push heroku main
